name: $(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2022

variables:
 - name: BuildConfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - group: 'Dotnet Core SDK Version'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - CalculateFunding.Generators.OrganisationGroup/*
    - CalculateFunding.Common.ApiClient.Policies/*
    - CalculateFunding.Common.ApiClient.Providers/*

pr:
  paths:
    include:
    - CalculateFunding.Generators.OrganisationGroup/*
    - CalculateFunding.Common.ApiClient.Policies/*
    - CalculateFunding.Common.ApiClient.Providers/*

steps:
- template: templates\nuget-package-build.yml
  parameters:
    DotNetCoreVersion: ${{ variables.DotnetCoreSdkVersionNet6 }}
    BuildConfiguration: ${{ variables.BuildConfiguration }}
    NugetProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Generators.OrganisationGroup\*.csproj'
    UnitTestProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Generators.OrganisationGroup.UnitTests\*.csproj'