name: $(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2022

variables:
 - name: BuildConfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - group: 'Dotnet Core SDK Version'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - CalculateFunding.Common.Config.ApiClient.Graph/*
    - CalculateFunding.Common.ApiClient.Graph/*
    - CalculateFunding.Common.Config.ApiClient/*
    - CalculateFunding.Common.ApiClient/*
    - CalculateFunding.Common.Models/*
    - CalculateFunding.Common/*

pr:
  paths:
    include:
    - CalculateFunding.Common.Config.ApiClient.Graph/*
    - CalculateFunding.Common.ApiClient.Graph/*
    - CalculateFunding.Common.Config.ApiClient/*
    - CalculateFunding.Common.ApiClient/*
    - CalculateFunding.Common.Models/*
    - CalculateFunding.Common/*

steps:
- template: templates\nuget-package-build.yml
  parameters:
    DotNetCoreVersion: ${{ variables.DotnetCoreSdkVersionNet8 }}
    BuildConfiguration: ${{ variables.BuildConfiguration }}
    NugetProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Common.Config.ApiClient.Graph\*.csproj'