name: $(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2019

variables:
 - name: BuildConfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - group: 'Dotnet Core SDK Version'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - CalculateFunding.Common.TemplateMetadata.Schema12/*
    - CalculateFunding.Common.TemplateMetadata/*
    - CalculateFunding.Common/*
    - CalculateFunding.TemplateMetaData.Schema12.UnitTests/*

pr:
  paths:
    include:
    - CalculateFunding.Common.TemplateMetadata.Schema12/*
    - CalculateFunding.Common.TemplateMetadata/*
    - CalculateFunding.Common/*
    - CalculateFunding.TemplateMetaData.Schema12.UnitTests/*

steps:
- template: templates\nuget-package-build.yml
  parameters:
    DotNetCoreVersion: ${{ variables.DotnetCoreSdkVersion }}
    BuildConfiguration: ${{ variables.BuildConfiguration }}
    NugetProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Common.TemplateMetadata.Schema12\*.csproj'
    UnitTestProjectPath: '$(System.DefaultWorkingDirectory)\*.TemplateMetadata.Schema12.UnitTests\*.csproj'
