name: $(Build.DefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: vs2017-win2016

variables:
 - name: BuildConfiguration
   value: 'release'
 - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
   value: true
 - name: DOTNET_CLI_TELEMETRY_OPTOUT 
   value: true
 - group: 'Dotnet Core SDK Version'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - CalculateFunding.Generators.Funding/*

pr:
  paths:
    include:
    - CalculateFunding.Generators.Funding/*

steps:
- template: templates\nuget-package-build.yml
  parameters:
    DotNetCoreVersion: ${{ variables.DotnetCoreSdkVersion }}
    BuildConfiguration: ${{ variables.BuildConfiguration }}
    NugetProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Generators.Funding\*.csproj'
    UnitTestProjectPath: '$(System.DefaultWorkingDirectory)\CalculateFunding.Generators.Funding.UnitTests\*.csproj'